In [1]:
from New_DRRP_Functions import *

L plate 1400 nm, 550 fps, 1.8 ms tint

In [2]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1400_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 10
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1400 = extracted_data[0]
Cal_Ir_1400 = extracted_data[1]
Cal_theta1400 = extracted_data[2]

In [3]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1400/"
lcenter = [322, 250]
rcenter = [322, 325]
maxradius = 10
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1400 = extracted_data[0]
Ir_1400 = extracted_data[1]
theta1400 = extracted_data[2]

In [4]:
data1400 = q_ultimate_polarimetry(Cal_theta1400, Cal_Il_1400, Cal_Ir_1400, theta1400, Il_1400, Ir_1400)
print(data1400[0], "This is the Mueller matrix of the sample waveplate")
print(data1400[1], "This is the retardance of the sample")
print(data1400[2], "This is the Mueller matrix for calibration (close to identity)")
print(data1400[3], "This is the RMS error in the calibration matrix")
print(data1400[4], "This is the retardance error in the sample waveplate")

[-0.12696364 -0.27399095 -0.17639755 -0.0467429  -0.04003094] Fit parameters for a1, w1, w2, r1, and r2. 1 for generator, 2 for analyzer
0.4266053904292495  This is the retardance found from the data after calibration.
[[ 0.93120961 -0.0050564   0.0010873  -0.001708  ]
 [-0.08487769  0.97404973 -0.15299718  0.03090947]
 [-0.02855165 -0.1147075  -1.          0.26619673]
 [-0.00856531 -0.01156611 -0.27688428 -0.8955405 ]] This is the Mueller matrix of the sample waveplate
0.4266053904292495 This is the retardance of the sample
[[ 0.89280856  0.00231881 -0.00542017 -0.000172  ]
 [-0.06411658  0.94988935  0.07194993 -0.00477985]
 [ 0.04213602 -0.03029912  1.         -0.01440441]
 [ 0.00244082 -0.00193954  0.00180343  0.89846216]] This is the Mueller matrix for calibration (close to identity)
0.010081125179608168 This is the RMS error in the calibration matrix
[0.0306021782440814, 0.061225588460240066] This is the retardance error in the sample waveplate


Divide by np.max(np.abs(M)) to normalize correctly

1500 nm, 

In [5]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1500_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 10
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1500 = extracted_data[0]
Cal_Ir_1500 = extracted_data[1]
Cal_theta1500 = extracted_data[2]

In [13]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1500/"
lcenter = [322, 250]
rcenter = [322, 325]
maxradius = 10
cutoff = 15000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1500 = extracted_data[0]
Ir_1500 = extracted_data[1]
theta1500 = extracted_data[2]

1550 nm

In [6]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1550_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 10
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1550 = extracted_data[0]
Cal_Ir_1550 = extracted_data[1]
Cal_theta1550 = extracted_data[2]

In [14]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1550/"
lcenter = [322, 252]
rcenter = [322, 327]
maxradius = 11
cutoff = 15000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1550 = extracted_data[0]
Ir_1550 = extracted_data[1]
theta1550 = extracted_data[2]

1600 nm

In [7]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1600_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 10
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1600 = extracted_data[0]
Cal_Ir_1600 = extracted_data[1]
Cal_theta1600 = extracted_data[2]

In [15]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1600/"
lcenter = [322, 250]
rcenter = [322, 327]
maxradius = 11
cutoff = 17000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1600 = extracted_data[0]
Ir_1600 = extracted_data[1]
theta1600 = extracted_data[2]

1620 nm

In [8]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1620_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 12
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1620 = extracted_data[0]
Cal_Ir_1620 = extracted_data[1]
Cal_theta1620 = extracted_data[2]

In [16]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1620/"
lcenter = [322, 250]
rcenter = [322, 327]
maxradius = 11
cutoff = 70000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1620 = extracted_data[0]
Ir_1620 = extracted_data[1]
theta1620 = extracted_data[2]

1650 nm

In [9]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1650_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 12
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1650 = extracted_data[0]
Cal_Ir_1650 = extracted_data[1]
Cal_theta1650 = extracted_data[2]

In [17]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1650/"
lcenter = [322, 250]
rcenter = [322, 327]
maxradius = 11
cutoff = 45000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1650 = extracted_data[0]
Ir_1650 = extracted_data[1]
theta1650 = extracted_data[2]

1750 nm

In [10]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1750_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 12
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1750 = extracted_data[0]
Cal_Ir_1750 = extracted_data[1]
Cal_theta1750 = extracted_data[2]

In [18]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1750/"
lcenter = [322, 250]
rcenter = [322, 327]
maxradius = 11
cutoff = 29000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1750 = extracted_data[0]
Ir_1750 = extracted_data[1]
theta1750 = extracted_data[2]

1900 nm

In [11]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_1900_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 12
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_1900 = extracted_data[0]
Cal_Ir_1900 = extracted_data[1]
Cal_theta1900 = extracted_data[2]

In [19]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_1900/"
lcenter = [322, 250]
rcenter = [322, 327]
maxradius = 11
cutoff = 21000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_1900 = extracted_data[0]
Ir_1900 = extracted_data[1]
theta1900 = extracted_data[2]

2000 nm

In [12]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Calibration/Calibration_Reduced/Cal_2000_Reduced/"
lcenter = [258, 255]
rcenter = [258, 332]
maxradius = 10
cutoff = 5000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Cal_Il_2000 = extracted_data[0]
Cal_Ir_2000 = extracted_data[1]
Cal_theta2000 = extracted_data[2]

In [20]:
reduced_filename = 'Reduced_DRRP_'
reduced_folder = "/home/shared/exoserver/Lab_Data/Mueller_Matrix_Polarimeter/L_Plate_Characterization/Reduced_Data/Reduced_L_2000/"
lcenter = [322, 250]
rcenter = [322, 327]
maxradius = 11
cutoff = 21000

extracted_data = extract_intensities(reduced_filename, reduced_folder, lcenter, rcenter, maxradius, cutoff)
Il_2000 = extracted_data[0]
Ir_2000 = extracted_data[1]
theta2000 = extracted_data[2]